specifyNetWeight porst 0
specifyNetWeight va 0
specifyNetWeight vb 23
specifyNetWeight vbg 5
specifyNetWeight VSS 29
specifyNetWeight vc 19
specifyNetWeight l17 1
specifyNetWeight l18 16
specifyNetWeight l19 11
specifyNetWeight l20 16
specifyNetWeight amp/vg 14
specifyNetWeight amp/vq 4
specifyNetWeight amp/vx 4
specifyNetWeight BGR_Core/vbneg 10
specifyNetWeight BGR_Core/l6 14
specifyNetWeight BGR_Core/l7 12
specifyNetWeight BGR_Core/l8 2
specifyNetWeight BGR_Core/l10 26
specifyNetWeight BGR_Core/l11 28
specifyNetWeight BGR_Core/l1 15
specifyNetWeight BGR_Core/l2 27
specifyNetWeight BGR_Core/l4 15
specifyNetWeight BGR_Core/l5 9
specifyNetWeight BGR_Core/l12 18
specifyNetWeight BGR_Core/R6/l 3
specifyNetWeight BGR_Core/R7/l 0
specifyNetWeight BGR_Core/R8/l 2
specifyNetWeight BGR_Core/R10/l 15
specifyNetWeight BGR_Core/R11/l 27
specifyNetWeight BGR_Core/R3/l 22
specifyNetWeight BGR_Core/R1/l 4
specifyNetWeight BGR_Core/R2/l 21
specifyNetWeight BGR_Core/R4/l 13
specifyNetWeight BGR_Core/R5/l 29
specifyNetWeight BGR_Core/R12/l 24
specifyNetWeight R17/l 11
specifyNetWeight R18/l 0
specifyNetWeight R19/l 27
specifyNetWeight R20/l 22
specifyNetWeight VDD 16
