specifyNetWeight porst 0
specifyNetWeight va 5
specifyNetWeight vb 11
specifyNetWeight vbg 22
specifyNetWeight VSS 4
specifyNetWeight vc 1
specifyNetWeight l17 9
specifyNetWeight l18 21
specifyNetWeight l19 7
specifyNetWeight l20 27
specifyNetWeight amp/vg 15
specifyNetWeight amp/vq 25
specifyNetWeight amp/vx 19
specifyNetWeight BGR_Core/vbneg 21
specifyNetWeight BGR_Core/l6 27
specifyNetWeight BGR_Core/l7 9
specifyNetWeight BGR_Core/l8 7
specifyNetWeight BGR_Core/l10 2
specifyNetWeight BGR_Core/l11 8
specifyNetWeight BGR_Core/l1 17
specifyNetWeight BGR_Core/l2 4
specifyNetWeight BGR_Core/l4 17
specifyNetWeight BGR_Core/l5 10
specifyNetWeight BGR_Core/l12 5
specifyNetWeight BGR_Core/R6/l 3
specifyNetWeight BGR_Core/R7/l 8
specifyNetWeight BGR_Core/R8/l 10
specifyNetWeight BGR_Core/R10/l 7
specifyNetWeight BGR_Core/R11/l 23
specifyNetWeight BGR_Core/R3/l 15
specifyNetWeight BGR_Core/R1/l 18
specifyNetWeight BGR_Core/R2/l 12
specifyNetWeight BGR_Core/R4/l 16
specifyNetWeight BGR_Core/R5/l 0
specifyNetWeight BGR_Core/R12/l 29
specifyNetWeight R17/l 17
specifyNetWeight R18/l 29
specifyNetWeight R19/l 24
specifyNetWeight R20/l 0
specifyNetWeight VDD 23
