specifyNetWeight porst 9
specifyNetWeight va 4
specifyNetWeight vb 22
specifyNetWeight vbg 16
specifyNetWeight VSS 16
specifyNetWeight vc 15
specifyNetWeight l17 5
specifyNetWeight l18 27
specifyNetWeight l19 1
specifyNetWeight l20 20
specifyNetWeight amp/vg 4
specifyNetWeight amp/vq 14
specifyNetWeight amp/vx 16
specifyNetWeight BGR_Core/vbneg 26
specifyNetWeight BGR_Core/l6 3
specifyNetWeight BGR_Core/l7 25
specifyNetWeight BGR_Core/l8 2
specifyNetWeight BGR_Core/l10 23
specifyNetWeight BGR_Core/l11 27
specifyNetWeight BGR_Core/l1 10
specifyNetWeight BGR_Core/l2 3
specifyNetWeight BGR_Core/l4 22
specifyNetWeight BGR_Core/l5 26
specifyNetWeight BGR_Core/l12 22
specifyNetWeight BGR_Core/R6/l 9
specifyNetWeight BGR_Core/R7/l 5
specifyNetWeight BGR_Core/R8/l 2
specifyNetWeight BGR_Core/R10/l 2
specifyNetWeight BGR_Core/R11/l 23
specifyNetWeight BGR_Core/R3/l 12
specifyNetWeight BGR_Core/R1/l 22
specifyNetWeight BGR_Core/R2/l 24
specifyNetWeight BGR_Core/R4/l 3
specifyNetWeight BGR_Core/R5/l 23
specifyNetWeight BGR_Core/R12/l 5
specifyNetWeight R17/l 6
specifyNetWeight R18/l 16
specifyNetWeight R19/l 21
specifyNetWeight R20/l 29
specifyNetWeight VDD 2
