specifyNetWeight porst 15
specifyNetWeight va 6
specifyNetWeight vb 28
specifyNetWeight vbg 15
specifyNetWeight VSS 3
specifyNetWeight vc 26
specifyNetWeight l17 26
specifyNetWeight l18 3
specifyNetWeight l19 20
specifyNetWeight l20 14
specifyNetWeight amp/vg 25
specifyNetWeight amp/vq 8
specifyNetWeight amp/vx 22
specifyNetWeight BGR_Core/vbneg 24
specifyNetWeight BGR_Core/l6 28
specifyNetWeight BGR_Core/l7 9
specifyNetWeight BGR_Core/l8 6
specifyNetWeight BGR_Core/l10 5
specifyNetWeight BGR_Core/l11 7
specifyNetWeight BGR_Core/l1 6
specifyNetWeight BGR_Core/l2 8
specifyNetWeight BGR_Core/l4 2
specifyNetWeight BGR_Core/l5 0
specifyNetWeight BGR_Core/l12 7
specifyNetWeight BGR_Core/R6/l 0
specifyNetWeight BGR_Core/R7/l 20
specifyNetWeight BGR_Core/R8/l 4
specifyNetWeight BGR_Core/R10/l 13
specifyNetWeight BGR_Core/R11/l 3
specifyNetWeight BGR_Core/R3/l 9
specifyNetWeight BGR_Core/R1/l 9
specifyNetWeight BGR_Core/R2/l 15
specifyNetWeight BGR_Core/R4/l 4
specifyNetWeight BGR_Core/R5/l 4
specifyNetWeight BGR_Core/R12/l 0
specifyNetWeight R17/l 14
specifyNetWeight R18/l 28
specifyNetWeight R19/l 22
specifyNetWeight R20/l 5
specifyNetWeight VDD 15
