specifyNetWeight porst 8
specifyNetWeight va 7
specifyNetWeight vb 10
specifyNetWeight vbg 22
specifyNetWeight VSS 0
specifyNetWeight vc 16
specifyNetWeight l17 16
specifyNetWeight l18 14
specifyNetWeight l19 9
specifyNetWeight l20 9
specifyNetWeight amp/vg 11
specifyNetWeight amp/vq 20
specifyNetWeight amp/vx 1
specifyNetWeight BGR_Core/vbneg 21
specifyNetWeight BGR_Core/l6 28
specifyNetWeight BGR_Core/l7 19
specifyNetWeight BGR_Core/l8 20
specifyNetWeight BGR_Core/l10 3
specifyNetWeight BGR_Core/l11 28
specifyNetWeight BGR_Core/l1 29
specifyNetWeight BGR_Core/l2 16
specifyNetWeight BGR_Core/l4 2
specifyNetWeight BGR_Core/l5 19
specifyNetWeight BGR_Core/l12 27
specifyNetWeight BGR_Core/R6/l 18
specifyNetWeight BGR_Core/R7/l 7
specifyNetWeight BGR_Core/R8/l 21
specifyNetWeight BGR_Core/R10/l 14
specifyNetWeight BGR_Core/R11/l 20
specifyNetWeight BGR_Core/R3/l 26
specifyNetWeight BGR_Core/R1/l 14
specifyNetWeight BGR_Core/R2/l 19
specifyNetWeight BGR_Core/R4/l 11
specifyNetWeight BGR_Core/R5/l 24
specifyNetWeight BGR_Core/R12/l 15
specifyNetWeight R17/l 25
specifyNetWeight R18/l 1
specifyNetWeight R19/l 10
specifyNetWeight R20/l 11
specifyNetWeight VDD 0
