specifyNetWeight porst 5
specifyNetWeight va 13
specifyNetWeight vb 14
specifyNetWeight vbg 21
specifyNetWeight VSS 24
specifyNetWeight vc 26
specifyNetWeight l17 23
specifyNetWeight l18 28
specifyNetWeight l19 22
specifyNetWeight l20 9
specifyNetWeight amp/vg 1
specifyNetWeight amp/vq 25
specifyNetWeight amp/vx 21
specifyNetWeight BGR_Core/vbneg 28
specifyNetWeight BGR_Core/l6 24
specifyNetWeight BGR_Core/l7 1
specifyNetWeight BGR_Core/l8 27
specifyNetWeight BGR_Core/l10 20
specifyNetWeight BGR_Core/l11 3
specifyNetWeight BGR_Core/l1 9
specifyNetWeight BGR_Core/l2 2
specifyNetWeight BGR_Core/l4 1
specifyNetWeight BGR_Core/l5 1
specifyNetWeight BGR_Core/l12 23
specifyNetWeight BGR_Core/R6/l 27
specifyNetWeight BGR_Core/R7/l 21
specifyNetWeight BGR_Core/R8/l 24
specifyNetWeight BGR_Core/R10/l 19
specifyNetWeight BGR_Core/R11/l 20
specifyNetWeight BGR_Core/R3/l 11
specifyNetWeight BGR_Core/R1/l 17
specifyNetWeight BGR_Core/R2/l 12
specifyNetWeight BGR_Core/R4/l 13
specifyNetWeight BGR_Core/R5/l 5
specifyNetWeight BGR_Core/R12/l 28
specifyNetWeight R17/l 10
specifyNetWeight R18/l 18
specifyNetWeight R19/l 0
specifyNetWeight R20/l 5
specifyNetWeight VDD 4
