specifyNetWeight porst 4
specifyNetWeight va 27
specifyNetWeight vb 20
specifyNetWeight vbg 14
specifyNetWeight VSS 18
specifyNetWeight vc 16
specifyNetWeight l17 1
specifyNetWeight l18 12
specifyNetWeight l19 10
specifyNetWeight l20 0
specifyNetWeight amp/vg 8
specifyNetWeight amp/vq 29
specifyNetWeight amp/vx 20
specifyNetWeight BGR_Core/vbneg 11
specifyNetWeight BGR_Core/l6 2
specifyNetWeight BGR_Core/l7 29
specifyNetWeight BGR_Core/l8 4
specifyNetWeight BGR_Core/l10 9
specifyNetWeight BGR_Core/l11 4
specifyNetWeight BGR_Core/l1 8
specifyNetWeight BGR_Core/l2 11
specifyNetWeight BGR_Core/l4 18
specifyNetWeight BGR_Core/l5 17
specifyNetWeight BGR_Core/l12 27
specifyNetWeight BGR_Core/R6/l 23
specifyNetWeight BGR_Core/R7/l 22
specifyNetWeight BGR_Core/R8/l 2
specifyNetWeight BGR_Core/R10/l 3
specifyNetWeight BGR_Core/R11/l 28
specifyNetWeight BGR_Core/R3/l 9
specifyNetWeight BGR_Core/R1/l 26
specifyNetWeight BGR_Core/R2/l 23
specifyNetWeight BGR_Core/R4/l 17
specifyNetWeight BGR_Core/R5/l 25
specifyNetWeight BGR_Core/R12/l 5
specifyNetWeight R17/l 22
specifyNetWeight R18/l 15
specifyNetWeight R19/l 9
specifyNetWeight R20/l 28
specifyNetWeight VDD 0
