specifyNetWeight porst 2
specifyNetWeight va 6
specifyNetWeight vb 27
specifyNetWeight vbg 3
specifyNetWeight VSS 8
specifyNetWeight vc 4
specifyNetWeight l17 20
specifyNetWeight l18 26
specifyNetWeight l19 24
specifyNetWeight l20 20
specifyNetWeight amp/vg 26
specifyNetWeight amp/vq 29
specifyNetWeight amp/vx 29
specifyNetWeight BGR_Core/vbneg 5
specifyNetWeight BGR_Core/l6 26
specifyNetWeight BGR_Core/l7 1
specifyNetWeight BGR_Core/l8 4
specifyNetWeight BGR_Core/l10 15
specifyNetWeight BGR_Core/l11 10
specifyNetWeight BGR_Core/l1 27
specifyNetWeight BGR_Core/l2 20
specifyNetWeight BGR_Core/l4 3
specifyNetWeight BGR_Core/l5 18
specifyNetWeight BGR_Core/l12 23
specifyNetWeight BGR_Core/R6/l 26
specifyNetWeight BGR_Core/R7/l 15
specifyNetWeight BGR_Core/R8/l 15
specifyNetWeight BGR_Core/R10/l 2
specifyNetWeight BGR_Core/R11/l 11
specifyNetWeight BGR_Core/R3/l 11
specifyNetWeight BGR_Core/R1/l 25
specifyNetWeight BGR_Core/R2/l 4
specifyNetWeight BGR_Core/R4/l 14
specifyNetWeight BGR_Core/R5/l 14
specifyNetWeight BGR_Core/R12/l 10
specifyNetWeight R17/l 7
specifyNetWeight R18/l 11
specifyNetWeight R19/l 26
specifyNetWeight R20/l 18
specifyNetWeight VDD 20
