#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : October 30, 2019
#

name: cadence-innovus-signoff

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

# inputs:
#   - innovus-foundation-flow
#   - adk
#   - design.checkpoint

outputs:
  - design.gds.gz
  - design-merged.gds
  - design.lvs.v
  - design.def.gz

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cat bgr-v0.gds.gz > outputs/design.gds.gz
  - cat bgr-v0-merged.gds> outputs/design-merged.gds
  - cat bgr-v0.lvs.v > outputs/design.lvs.v
  - cat bgr-v0.def.gz > outputs/design.def.gz
