specifyNetWeight porst 7
specifyNetWeight va 23
specifyNetWeight vb 12
specifyNetWeight vbg 22
specifyNetWeight VSS 24
specifyNetWeight vc 28
specifyNetWeight l17 2
specifyNetWeight l18 16
specifyNetWeight l19 25
specifyNetWeight l20 27
specifyNetWeight amp/vg 6
specifyNetWeight amp/vq 1
specifyNetWeight amp/vx 5
specifyNetWeight BGR_Core/vbneg 25
specifyNetWeight BGR_Core/l6 17
specifyNetWeight BGR_Core/l7 2
specifyNetWeight BGR_Core/l8 14
specifyNetWeight BGR_Core/l10 25
specifyNetWeight BGR_Core/l11 25
specifyNetWeight BGR_Core/l1 29
specifyNetWeight BGR_Core/l2 27
specifyNetWeight BGR_Core/l4 23
specifyNetWeight BGR_Core/l5 3
specifyNetWeight BGR_Core/l12 16
specifyNetWeight BGR_Core/R6/l 23
specifyNetWeight BGR_Core/R7/l 15
specifyNetWeight BGR_Core/R8/l 2
specifyNetWeight BGR_Core/R10/l 5
specifyNetWeight BGR_Core/R11/l 19
specifyNetWeight BGR_Core/R3/l 26
specifyNetWeight BGR_Core/R1/l 5
specifyNetWeight BGR_Core/R2/l 0
specifyNetWeight BGR_Core/R4/l 1
specifyNetWeight BGR_Core/R5/l 14
specifyNetWeight BGR_Core/R12/l 19
specifyNetWeight R17/l 19
specifyNetWeight R18/l 6
specifyNetWeight R19/l 6
specifyNetWeight R20/l 28
specifyNetWeight VDD 4
