specifyNetWeight porst 14
specifyNetWeight va 5
specifyNetWeight vb 23
specifyNetWeight vbg 15
specifyNetWeight VSS 14
specifyNetWeight vc 18
specifyNetWeight l17 8
specifyNetWeight l18 21
specifyNetWeight l19 4
specifyNetWeight l20 16
specifyNetWeight amp/vg 15
specifyNetWeight amp/vq 12
specifyNetWeight amp/vx 3
specifyNetWeight BGR_Core/vbneg 2
specifyNetWeight BGR_Core/l6 29
specifyNetWeight BGR_Core/l7 2
specifyNetWeight BGR_Core/l8 14
specifyNetWeight BGR_Core/l10 6
specifyNetWeight BGR_Core/l11 20
specifyNetWeight BGR_Core/l1 21
specifyNetWeight BGR_Core/l2 28
specifyNetWeight BGR_Core/l4 5
specifyNetWeight BGR_Core/l5 5
specifyNetWeight BGR_Core/l12 3
specifyNetWeight BGR_Core/R6/l 0
specifyNetWeight BGR_Core/R7/l 5
specifyNetWeight BGR_Core/R8/l 18
specifyNetWeight BGR_Core/R10/l 23
specifyNetWeight BGR_Core/R11/l 3
specifyNetWeight BGR_Core/R3/l 27
specifyNetWeight BGR_Core/R1/l 0
specifyNetWeight BGR_Core/R2/l 24
specifyNetWeight BGR_Core/R4/l 24
specifyNetWeight BGR_Core/R5/l 21
specifyNetWeight BGR_Core/R12/l 2
specifyNetWeight R17/l 18
specifyNetWeight R18/l 12
specifyNetWeight R19/l 15
specifyNetWeight R20/l 0
specifyNetWeight VDD 29
