specifyNetWeight porst 27
specifyNetWeight va 2
specifyNetWeight vb 23
specifyNetWeight vbg 9
specifyNetWeight VSS 8
specifyNetWeight vc 13
specifyNetWeight l17 6
specifyNetWeight l18 21
specifyNetWeight l19 22
specifyNetWeight l20 4
specifyNetWeight amp/vg 17
specifyNetWeight amp/vq 2
specifyNetWeight amp/vx 6
specifyNetWeight BGR_Core/vbneg 19
specifyNetWeight BGR_Core/l6 8
specifyNetWeight BGR_Core/l7 1
specifyNetWeight BGR_Core/l8 4
specifyNetWeight BGR_Core/l10 12
specifyNetWeight BGR_Core/l11 29
specifyNetWeight BGR_Core/l1 14
specifyNetWeight BGR_Core/l2 26
specifyNetWeight BGR_Core/l4 7
specifyNetWeight BGR_Core/l5 27
specifyNetWeight BGR_Core/l12 26
specifyNetWeight BGR_Core/R6/l 12
specifyNetWeight BGR_Core/R7/l 7
specifyNetWeight BGR_Core/R8/l 11
specifyNetWeight BGR_Core/R10/l 28
specifyNetWeight BGR_Core/R11/l 23
specifyNetWeight BGR_Core/R3/l 22
specifyNetWeight BGR_Core/R1/l 5
specifyNetWeight BGR_Core/R2/l 15
specifyNetWeight BGR_Core/R4/l 4
specifyNetWeight BGR_Core/R5/l 4
specifyNetWeight BGR_Core/R12/l 16
specifyNetWeight R17/l 13
specifyNetWeight R18/l 21
specifyNetWeight R19/l 5
specifyNetWeight R20/l 18
specifyNetWeight VDD 2
