specifyNetWeight porst 16
specifyNetWeight va 14
specifyNetWeight vb 1
specifyNetWeight vbg 6
specifyNetWeight VSS 29
specifyNetWeight vc 13
specifyNetWeight l17 20
specifyNetWeight l18 18
specifyNetWeight l19 15
specifyNetWeight l20 13
specifyNetWeight amp/vg 17
specifyNetWeight amp/vq 0
specifyNetWeight amp/vx 24
specifyNetWeight BGR_Core/vbneg 3
specifyNetWeight BGR_Core/l6 20
specifyNetWeight BGR_Core/l7 4
specifyNetWeight BGR_Core/l8 4
specifyNetWeight BGR_Core/l10 4
specifyNetWeight BGR_Core/l11 13
specifyNetWeight BGR_Core/l1 8
specifyNetWeight BGR_Core/l2 27
specifyNetWeight BGR_Core/l4 0
specifyNetWeight BGR_Core/l5 2
specifyNetWeight BGR_Core/l12 20
specifyNetWeight BGR_Core/R6/l 27
specifyNetWeight BGR_Core/R7/l 19
specifyNetWeight BGR_Core/R8/l 13
specifyNetWeight BGR_Core/R10/l 27
specifyNetWeight BGR_Core/R11/l 14
specifyNetWeight BGR_Core/R3/l 28
specifyNetWeight BGR_Core/R1/l 13
specifyNetWeight BGR_Core/R2/l 27
specifyNetWeight BGR_Core/R4/l 0
specifyNetWeight BGR_Core/R5/l 28
specifyNetWeight BGR_Core/R12/l 3
specifyNetWeight R17/l 4
specifyNetWeight R18/l 19
specifyNetWeight R19/l 23
specifyNetWeight R20/l 1
specifyNetWeight VDD 2
