specifyNetWeight porst 3
specifyNetWeight va 20
specifyNetWeight vb 28
specifyNetWeight vbg 1
specifyNetWeight VSS 6
specifyNetWeight vc 15
specifyNetWeight l17 24
specifyNetWeight l18 0
specifyNetWeight l19 22
specifyNetWeight l20 21
specifyNetWeight amp/vg 12
specifyNetWeight amp/vq 21
specifyNetWeight amp/vx 6
specifyNetWeight BGR_Core/vbneg 18
specifyNetWeight BGR_Core/l6 25
specifyNetWeight BGR_Core/l7 22
specifyNetWeight BGR_Core/l8 7
specifyNetWeight BGR_Core/l10 26
specifyNetWeight BGR_Core/l11 7
specifyNetWeight BGR_Core/l1 7
specifyNetWeight BGR_Core/l2 27
specifyNetWeight BGR_Core/l4 27
specifyNetWeight BGR_Core/l5 3
specifyNetWeight BGR_Core/l12 13
specifyNetWeight BGR_Core/R6/l 2
specifyNetWeight BGR_Core/R7/l 8
specifyNetWeight BGR_Core/R8/l 4
specifyNetWeight BGR_Core/R10/l 25
specifyNetWeight BGR_Core/R11/l 21
specifyNetWeight BGR_Core/R3/l 27
specifyNetWeight BGR_Core/R1/l 23
specifyNetWeight BGR_Core/R2/l 11
specifyNetWeight BGR_Core/R4/l 15
specifyNetWeight BGR_Core/R5/l 24
specifyNetWeight BGR_Core/R12/l 0
specifyNetWeight R17/l 17
specifyNetWeight R18/l 23
specifyNetWeight R19/l 9
specifyNetWeight R20/l 13
specifyNetWeight VDD 2
