specifyNetWeight porst 24
specifyNetWeight va 4
specifyNetWeight vb 1
specifyNetWeight vbg 16
specifyNetWeight VSS 18
specifyNetWeight vc 7
specifyNetWeight l17 26
specifyNetWeight l18 26
specifyNetWeight l19 16
specifyNetWeight l20 7
specifyNetWeight amp/vg 26
specifyNetWeight amp/vq 29
specifyNetWeight amp/vx 17
specifyNetWeight BGR_Core/vbneg 1
specifyNetWeight BGR_Core/l6 14
specifyNetWeight BGR_Core/l7 0
specifyNetWeight BGR_Core/l8 3
specifyNetWeight BGR_Core/l10 16
specifyNetWeight BGR_Core/l11 17
specifyNetWeight BGR_Core/l1 21
specifyNetWeight BGR_Core/l2 27
specifyNetWeight BGR_Core/l4 10
specifyNetWeight BGR_Core/l5 0
specifyNetWeight BGR_Core/l12 11
specifyNetWeight BGR_Core/R6/l 4
specifyNetWeight BGR_Core/R7/l 9
specifyNetWeight BGR_Core/R8/l 6
specifyNetWeight BGR_Core/R10/l 25
specifyNetWeight BGR_Core/R11/l 10
specifyNetWeight BGR_Core/R3/l 5
specifyNetWeight BGR_Core/R1/l 8
specifyNetWeight BGR_Core/R2/l 2
specifyNetWeight BGR_Core/R4/l 7
specifyNetWeight BGR_Core/R5/l 1
specifyNetWeight BGR_Core/R12/l 7
specifyNetWeight R17/l 0
specifyNetWeight R18/l 20
specifyNetWeight R19/l 4
specifyNetWeight R20/l 12
specifyNetWeight VDD 8
