specifyNetWeight porst 17
specifyNetWeight va 12
specifyNetWeight vb 3
specifyNetWeight vbg 19
specifyNetWeight VSS 3
specifyNetWeight vc 16
specifyNetWeight l17 20
specifyNetWeight l18 9
specifyNetWeight l19 13
specifyNetWeight l20 11
specifyNetWeight amp/vg 11
specifyNetWeight amp/vq 13
specifyNetWeight amp/vx 20
specifyNetWeight VNW 6
specifyNetWeight VDDPST 11
specifyNetWeight POC 17
specifyNetWeight VDDCE 15
specifyNetWeight VDDPE 8
specifyNetWeight VPW 11
specifyNetWeight VSSPST 7
specifyNetWeight VSSE 12
specifyNetWeight BGR_Core/vbneg 7
specifyNetWeight BGR_Core/l6 9
specifyNetWeight BGR_Core/l7 11
specifyNetWeight BGR_Core/l8 16
specifyNetWeight BGR_Core/l10 14
specifyNetWeight BGR_Core/l11 3
specifyNetWeight BGR_Core/l1 15
specifyNetWeight BGR_Core/l2 3
specifyNetWeight BGR_Core/l4 14
specifyNetWeight BGR_Core/l5 5
specifyNetWeight BGR_Core/l12 19
specifyNetWeight BGR_Core/R6/l 3
specifyNetWeight BGR_Core/R7/l 7
specifyNetWeight BGR_Core/R8/l 16
specifyNetWeight BGR_Core/R10/l 4
specifyNetWeight BGR_Core/R11/l 8
specifyNetWeight BGR_Core/R3/l 2
specifyNetWeight BGR_Core/R1/l 16
specifyNetWeight BGR_Core/R2/l 18
specifyNetWeight BGR_Core/R4/l 17
specifyNetWeight BGR_Core/R5/l 19
specifyNetWeight BGR_Core/R12/l 6
specifyNetWeight R17/l 13
specifyNetWeight R18/l 17
specifyNetWeight R19/l 12
specifyNetWeight R20/l 11
specifyNetWeight VDD 16