specifyNetWeight porst 5
specifyNetWeight va 4
specifyNetWeight vb 28
specifyNetWeight vbg 9
specifyNetWeight VSS 23
specifyNetWeight vc 29
specifyNetWeight l17 5
specifyNetWeight l18 0
specifyNetWeight l19 7
specifyNetWeight l20 27
specifyNetWeight amp/vg 26
specifyNetWeight amp/vq 3
specifyNetWeight amp/vx 28
specifyNetWeight BGR_Core/vbneg 25
specifyNetWeight BGR_Core/l6 26
specifyNetWeight BGR_Core/l7 15
specifyNetWeight BGR_Core/l8 20
specifyNetWeight BGR_Core/l10 16
specifyNetWeight BGR_Core/l11 22
specifyNetWeight BGR_Core/l1 0
specifyNetWeight BGR_Core/l2 21
specifyNetWeight BGR_Core/l4 7
specifyNetWeight BGR_Core/l5 23
specifyNetWeight BGR_Core/l12 4
specifyNetWeight BGR_Core/R6/l 10
specifyNetWeight BGR_Core/R7/l 28
specifyNetWeight BGR_Core/R8/l 22
specifyNetWeight BGR_Core/R10/l 19
specifyNetWeight BGR_Core/R11/l 18
specifyNetWeight BGR_Core/R3/l 3
specifyNetWeight BGR_Core/R1/l 15
specifyNetWeight BGR_Core/R2/l 25
specifyNetWeight BGR_Core/R4/l 10
specifyNetWeight BGR_Core/R5/l 26
specifyNetWeight BGR_Core/R12/l 0
specifyNetWeight R17/l 5
specifyNetWeight R18/l 11
specifyNetWeight R19/l 12
specifyNetWeight R20/l 11
specifyNetWeight VDD 14
