specifyNetWeight porst 16
specifyNetWeight va 12
specifyNetWeight vb 7
specifyNetWeight vbg 9
specifyNetWeight VSS 23
specifyNetWeight vc 25
specifyNetWeight l17 15
specifyNetWeight l18 29
specifyNetWeight l19 15
specifyNetWeight l20 16
specifyNetWeight amp/vg 11
specifyNetWeight amp/vq 2
specifyNetWeight amp/vx 7
specifyNetWeight BGR_Core/vbneg 16
specifyNetWeight BGR_Core/l6 23
specifyNetWeight BGR_Core/l7 3
specifyNetWeight BGR_Core/l8 12
specifyNetWeight BGR_Core/l10 19
specifyNetWeight BGR_Core/l11 24
specifyNetWeight BGR_Core/l1 11
specifyNetWeight BGR_Core/l2 9
specifyNetWeight BGR_Core/l4 24
specifyNetWeight BGR_Core/l5 1
specifyNetWeight BGR_Core/l12 16
specifyNetWeight BGR_Core/R6/l 11
specifyNetWeight BGR_Core/R7/l 25
specifyNetWeight BGR_Core/R8/l 20
specifyNetWeight BGR_Core/R10/l 28
specifyNetWeight BGR_Core/R11/l 6
specifyNetWeight BGR_Core/R3/l 27
specifyNetWeight BGR_Core/R1/l 7
specifyNetWeight BGR_Core/R2/l 15
specifyNetWeight BGR_Core/R4/l 25
specifyNetWeight BGR_Core/R5/l 20
specifyNetWeight BGR_Core/R12/l 26
specifyNetWeight R17/l 10
specifyNetWeight R18/l 3
specifyNetWeight R19/l 15
specifyNetWeight R20/l 19
specifyNetWeight VDD 12
