/*
###############################################################
#  Generated by:      Cadence Innovus 20.13-s083_1
#  OS:                Linux x86_64(Host ID rice-503-20-north)
#  Generated on:      Sat May 28 19:13:35 2022
#  Design:            bgr_top
#  Command:           saveNetlist -excludeLeafCell -flat -phys /home/users/xingyuni/ee372/aloe-sky130/aloe/layout/output/lvs/bgr-v0.lvs.v
###############################################################
*/
module bgr_top (
	porst, 
	va, 
	vb, 
	vbg, 
	VDD, 
	VSS);
   inout porst;
   inout va;
   inout vb;
   inout vbg;
   inout VDD;
   inout VSS;

   // Internal wires
   wire vc;
   wire l17;
   wire l18;
   wire l19;
   wire l20;
   wire \amp/vg ;
   wire \amp/vq ;
   wire \amp/vx ;
   wire \BGR_Core/vbneg ;
   wire \BGR_Core/l6 ;
   wire \BGR_Core/l7 ;
   wire \BGR_Core/l8 ;
   wire \BGR_Core/l10 ;
   wire \BGR_Core/l11 ;
   wire \BGR_Core/l1 ;
   wire \BGR_Core/l2 ;
   wire \BGR_Core/l4 ;
   wire \BGR_Core/l5 ;
   wire \BGR_Core/l12 ;
   wire \BGR_Core/R6/l ;
   wire \BGR_Core/R7/l ;
   wire \BGR_Core/R8/l ;
   wire \BGR_Core/R10/l ;
   wire \BGR_Core/R11/l ;
   wire \BGR_Core/R3/l ;
   wire \BGR_Core/R1/l ;
   wire \BGR_Core/R2/l ;
   wire \BGR_Core/R4/l ;
   wire \BGR_Core/R5/l ;
   wire \BGR_Core/R12/l ;
   wire \R17/l ;
   wire \R18/l ;
   wire \R19/l ;
   wire \R20/l ;
   wire VNW;
   wire VDDPST;
   wire POC;
   wire VDDCE;
   wire VDDPE;
   wire VPW;
   wire VSSPST;
   wire VSSE;

   // Module instantiations
   sky130_asc_pfet_01v8_lvt_6 \amp/M4  (
	.SOURCE(VDD),
	.GATE(\amp/vg ),
	.DRAIN(\amp/vg ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pfet_01v8_lvt_6 \amp/M8  (
	.SOURCE(VDD),
	.GATE(\amp/vg ),
	.DRAIN(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_nfet_01v8_lvt_9 \amp/M9  (
	.SOURCE(\amp/vq ),
	.GATE(vb),
	.DRAIN(\amp/vg ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_nfet_01v8_lvt_9 \amp/M5  (
	.SOURCE(\amp/vq ),
	.GATE(va),
	.DRAIN(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_nfet_01v8_lvt_1 \amp/M6  (
	.SOURCE(VSS),
	.GATE(\amp/vx ),
	.DRAIN(\amp/vq ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_nfet_01v8_lvt_1 \amp/M7  (
	.SOURCE(VSS),
	.GATE(\amp/vx ),
	.DRAIN(\amp/vx ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pfet_01v8_lvt_12 \amp/M13  (
	.SOURCE(VDD),
	.GATE(vc),
	.DRAIN(\amp/vx ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \BGR_Core/C2/CA1  (
	.Cin(va),
	.Cout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \BGR_Core/C2/CA2  (
	.Cin(va),
	.Cout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \BGR_Core/C2/CA3  (
	.Cin(va),
	.Cout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \BGR_Core/C2/CA4  (
	.Cin(va),
	.Cout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \BGR_Core/C2/CA5  (
	.Cin(va),
	.Cout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R6/sub1  (
	.Rin(va),
	.Rout(\BGR_Core/R6/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R6/sub2  (
	.Rin(\BGR_Core/R6/l ),
	.Rout(\BGR_Core/l6 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R7/sub1  (
	.Rin(\BGR_Core/l6 ),
	.Rout(\BGR_Core/R7/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R7/sub2  (
	.Rin(\BGR_Core/R7/l ),
	.Rout(\BGR_Core/l7 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R8/sub1  (
	.Rin(\BGR_Core/l7 ),
	.Rout(\BGR_Core/R8/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R8/sub2  (
	.Rin(\BGR_Core/R8/l ),
	.Rout(\BGR_Core/l8 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R10/sub1  (
	.Rin(\BGR_Core/l8 ),
	.Rout(\BGR_Core/R10/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R10/sub2  (
	.Rin(\BGR_Core/R10/l ),
	.Rout(\BGR_Core/l10 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R11/sub1  (
	.Rin(\BGR_Core/l10 ),
	.Rout(\BGR_Core/R11/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R11/sub2  (
	.Rin(\BGR_Core/R11/l ),
	.Rout(\BGR_Core/l11 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_2 \BGR_Core/R9  (
	.Rin(\BGR_Core/l11 ),
	.Rout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pnp_05v5_W3p40L3p40_1 \BGR_Core/pnp_va  (
	.Emitter(va),
	.Collector(VSS),
	.Base(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R3/sub1  (
	.Rin(vb),
	.Rout(\BGR_Core/R3/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R3/sub2  (
	.Rin(\BGR_Core/R3/l ),
	.Rout(\BGR_Core/vbneg ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pnp_05v5_W3p40L3p40_8 \BGR_Core/pnp_vb/b1  (
	.Emitter(\BGR_Core/vbneg ),
	.Collector(VSS),
	.Base(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pnp_05v5_W3p40L3p40_8 \BGR_Core/pnp_vb/b2  (
	.Emitter(\BGR_Core/vbneg ),
	.Collector(VSS),
	.Base(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pnp_05v5_W3p40L3p40_8 \BGR_Core/pnp_vb/b3  (
	.Emitter(\BGR_Core/vbneg ),
	.Collector(VSS),
	.Base(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pnp_05v5_W3p40L3p40_8 \BGR_Core/pnp_vb/b4  (
	.Emitter(\BGR_Core/vbneg ),
	.Collector(VSS),
	.Base(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pnp_05v5_W3p40L3p40_7 \BGR_Core/pnp_vb/b5  (
	.Emitter(\BGR_Core/vbneg ),
	.Collector(VSS),
	.Base(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R1/sub1  (
	.Rin(\BGR_Core/l1 ),
	.Rout(\BGR_Core/R1/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R1/sub2  (
	.Rin(\BGR_Core/R1/l ),
	.Rout(vb), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R2/sub1  (
	.Rin(\BGR_Core/l1 ),
	.Rout(\BGR_Core/R2/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R2/sub2  (
	.Rin(\BGR_Core/R2/l ),
	.Rout(\BGR_Core/l2 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R4/sub1  (
	.Rin(\BGR_Core/l2 ),
	.Rout(\BGR_Core/R4/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R4/sub2  (
	.Rin(\BGR_Core/R4/l ),
	.Rout(\BGR_Core/l4 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R5/sub1  (
	.Rin(\BGR_Core/l4 ),
	.Rout(\BGR_Core/R5/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R5/sub2  (
	.Rin(\BGR_Core/R5/l ),
	.Rout(\BGR_Core/l5 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R12/sub1  (
	.Rin(\BGR_Core/l5 ),
	.Rout(\BGR_Core/R12/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \BGR_Core/R12/sub2  (
	.Rin(\BGR_Core/R12/l ),
	.Rout(\BGR_Core/l12 ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_2 \BGR_Core/R13  (
	.Rin(\BGR_Core/l12 ),
	.Rout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \CM/C1/CA1  (
	.Cin(VDD),
	.Cout(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \CM/C1/CA2  (
	.Cin(VDD),
	.Cout(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \CM/C1/CA3  (
	.Cin(VDD),
	.Cout(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \CM/C1/CA4  (
	.Cin(VDD),
	.Cout(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_cap_mim_m3_1 \CM/C1/CA5  (
	.Cin(VDD),
	.Cout(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pfet_01v8_lvt_12 \CM/M17  (
	.SOURCE(VDD),
	.GATE(VDD),
	.DRAIN(va), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pfet_01v8_lvt_60 \CM/M1  (
	.SOURCE(VDD),
	.GATE(vc),
	.DRAIN(va), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pfet_01v8_lvt_60 \CM/M2  (
	.SOURCE(VDD),
	.GATE(vc),
	.DRAIN(vb), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_pfet_01v8_lvt_60 \CM/M3  (
	.SOURCE(VDD),
	.GATE(vc),
	.DRAIN(vbg), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_nfet_01v8_lvt_9 M10 (
	.SOURCE(VSS),
	.GATE(porst),
	.DRAIN(vc), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R17/sub1  (
	.Rin(vbg),
	.Rout(\R17/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R17/sub2  (
	.Rin(\R17/l ),
	.Rout(l17), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R18/sub1  (
	.Rin(l17),
	.Rout(\R18/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R18/sub2  (
	.Rin(\R18/l ),
	.Rout(l18), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R19/sub1  (
	.Rin(l18),
	.Rout(\R19/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R19/sub2  (
	.Rin(\R19/l ),
	.Rout(l19), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R20/sub1  (
	.Rin(l19),
	.Rout(\R20/l ), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 \R20/sub2  (
	.Rin(\R20/l ),
	.Rout(l20), 
	.VPWR(VDD), 
	.VGND(VSS));
   sky130_asc_res_xhigh_po_2p85_1 R21 (
	.Rin(l20),
	.Rout(VSS), 
	.VPWR(VDD), 
	.VGND(VSS));
endmodule

