specifyNetWeight porst 15
specifyNetWeight va 12
specifyNetWeight vb 8
specifyNetWeight vbg 27
specifyNetWeight VSS 7
specifyNetWeight vc 2
specifyNetWeight l17 10
specifyNetWeight l18 13
specifyNetWeight l19 3
specifyNetWeight l20 17
specifyNetWeight amp/vg 3
specifyNetWeight amp/vq 19
specifyNetWeight amp/vx 7
specifyNetWeight BGR_Core/vbneg 22
specifyNetWeight BGR_Core/l6 8
specifyNetWeight BGR_Core/l7 7
specifyNetWeight BGR_Core/l8 6
specifyNetWeight BGR_Core/l10 4
specifyNetWeight BGR_Core/l11 29
specifyNetWeight BGR_Core/l1 26
specifyNetWeight BGR_Core/l2 4
specifyNetWeight BGR_Core/l4 23
specifyNetWeight BGR_Core/l5 29
specifyNetWeight BGR_Core/l12 2
specifyNetWeight BGR_Core/R6/l 3
specifyNetWeight BGR_Core/R7/l 8
specifyNetWeight BGR_Core/R8/l 15
specifyNetWeight BGR_Core/R10/l 11
specifyNetWeight BGR_Core/R11/l 6
specifyNetWeight BGR_Core/R3/l 1
specifyNetWeight BGR_Core/R1/l 29
specifyNetWeight BGR_Core/R2/l 20
specifyNetWeight BGR_Core/R4/l 15
specifyNetWeight BGR_Core/R5/l 17
specifyNetWeight BGR_Core/R12/l 6
specifyNetWeight R17/l 7
specifyNetWeight R18/l 17
specifyNetWeight R19/l 28
specifyNetWeight R20/l 21
specifyNetWeight VDD 13
