specifyNetWeight porst 8
specifyNetWeight va 13
specifyNetWeight vb 0
specifyNetWeight vbg 6
specifyNetWeight VSS 27
specifyNetWeight vc 19
specifyNetWeight l17 15
specifyNetWeight l18 11
specifyNetWeight l19 8
specifyNetWeight l20 2
specifyNetWeight amp/vg 12
specifyNetWeight amp/vq 18
specifyNetWeight amp/vx 16
specifyNetWeight BGR_Core/vbneg 16
specifyNetWeight BGR_Core/l6 20
specifyNetWeight BGR_Core/l7 28
specifyNetWeight BGR_Core/l8 12
specifyNetWeight BGR_Core/l10 10
specifyNetWeight BGR_Core/l11 3
specifyNetWeight BGR_Core/l1 12
specifyNetWeight BGR_Core/l2 29
specifyNetWeight BGR_Core/l4 7
specifyNetWeight BGR_Core/l5 11
specifyNetWeight BGR_Core/l12 21
specifyNetWeight BGR_Core/R6/l 17
specifyNetWeight BGR_Core/R7/l 12
specifyNetWeight BGR_Core/R8/l 20
specifyNetWeight BGR_Core/R10/l 15
specifyNetWeight BGR_Core/R11/l 1
specifyNetWeight BGR_Core/R3/l 13
specifyNetWeight BGR_Core/R1/l 13
specifyNetWeight BGR_Core/R2/l 5
specifyNetWeight BGR_Core/R4/l 24
specifyNetWeight BGR_Core/R5/l 23
specifyNetWeight BGR_Core/R12/l 7
specifyNetWeight R17/l 3
specifyNetWeight R18/l 4
specifyNetWeight R19/l 20
specifyNetWeight R20/l 17
specifyNetWeight VDD 16
