specifyNetWeight porst 14
specifyNetWeight va 22
specifyNetWeight vb 16
specifyNetWeight vbg 9
specifyNetWeight VSS 22
specifyNetWeight vc 9
specifyNetWeight l17 0
specifyNetWeight l18 10
specifyNetWeight l19 10
specifyNetWeight l20 13
specifyNetWeight amp/vg 16
specifyNetWeight amp/vq 13
specifyNetWeight amp/vx 6
specifyNetWeight BGR_Core/vbneg 10
specifyNetWeight BGR_Core/l6 21
specifyNetWeight BGR_Core/l7 26
specifyNetWeight BGR_Core/l8 19
specifyNetWeight BGR_Core/l10 6
specifyNetWeight BGR_Core/l11 25
specifyNetWeight BGR_Core/l1 21
specifyNetWeight BGR_Core/l2 14
specifyNetWeight BGR_Core/l4 16
specifyNetWeight BGR_Core/l5 6
specifyNetWeight BGR_Core/l12 1
specifyNetWeight BGR_Core/R6/l 4
specifyNetWeight BGR_Core/R7/l 8
specifyNetWeight BGR_Core/R8/l 6
specifyNetWeight BGR_Core/R10/l 11
specifyNetWeight BGR_Core/R11/l 28
specifyNetWeight BGR_Core/R3/l 20
specifyNetWeight BGR_Core/R1/l 18
specifyNetWeight BGR_Core/R2/l 20
specifyNetWeight BGR_Core/R4/l 14
specifyNetWeight BGR_Core/R5/l 22
specifyNetWeight BGR_Core/R12/l 23
specifyNetWeight R17/l 14
specifyNetWeight R18/l 23
specifyNetWeight R19/l 6
specifyNetWeight R20/l 20
specifyNetWeight VDD 25
